Add oresat.conf with extlinux section for image builder

diff --git a/image_builder/Makefile b/image_builder/Makefile
--- a/image_builder/Makefile
+++ b/image_builder/Makefile
@@ -1,12 +1,10 @@
 UBOOT_REPO= u-boot
 IMAGE_BUILDER_REPO= image-builder
 DEVICE_TREES= ../device_trees
-CONFIG= ../../am335x_oresat_defconfig
+CONFIG= am335x_oresat.config
 BOOTLOADER_DIR= oresat_bootloader
-PATCH_FILE= oresat_extlinux.patch
-TARGET_FILE= image-builder/tools/setup_sdcard.sh
 
-.PHONY: all image_builder uboot config clone clean
+.PHONY: all uboot device_trees test clean
 
 ARCH= $(shell uname -m)
 ifeq ($(ARCH), armv7l)
@@ -15,35 +13,34 @@ else
 	FLAGS= ARCH=arm CROSS_COMPILE=arm-none-eabi-
 endif
 
-all: clone config uboot
-
-image_builder: uboot 
+all: test uboot
 	./build_images.sh $(board)
 
-uboot: config
-	mkdir -p $(BOOTLOADER_DIR);
+uboot: device_trees
+	mkdir -p $(BOOTLOADER_DIR)
 	@if [ ! -f "$(BOOTLOADER_DIR)/MLO" ] || \
 			[ ! -f "$(BOOTLOADER_DIR)/u-boot-dtb.img" ]; then \
+		cp $(CONFIG) $(UBOOT_REPO)/.config; \
 		make -C $(UBOOT_REPO) $(FLAGS); \
 		mv $(UBOOT_REPO)/MLO $(BOOTLOADER_DIR); \
 		mv $(UBOOT_REPO)/*.img $(BOOTLOADER_DIR); \
 	fi
 
-config: clone
-	make -C $(UBOOT_REPO) $(FLAGS) $(CONFIG)
+device_trees:
+	make -C $(DEVICE_TREES)
 
-clone:
-	@if [ -z "$( ls -A $(IMAGE_BUILDER_REPO) )" ] || \
-			[ -z "$( ls -A $(UBOOT_REPO) )" ]; then \
-		git submodule update --init; \
-		if patch -N -i $(PATCH_FILE) $(TARGET_FILE) > /dev/null 2>&1; then \
-			echo "$(TARGET_FILE) patched!"; \
-		fi \
-	fi
+test:
+ifeq ($(wildcard $(UBOOT_REPO)/*)$(wildcard $(IMAGE_BUILDER_REPO)/*),)
+	@echo "Build failed, missing dependency..."
+	@echo "Hint: git submodule update --init"
+	@exit 1 
+endif
 
 clean:
 	rm -rf $(BOOTLOADER_DIR)/*
-	rm $(IMAGE_BUILDER_REPO)/configs/oresat*
-	rm $(IMAGE_BUILDER_REPO)/target/chroot/oresat*
-	rm $(IMAGE_BUILDER_REPO)/tools/setup_sdcard.sh.rej
+	rm -f $(IMAGE_BUILDER_REPO)/configs/oresat*
+	rm -f $(IMAGE_BUILDER_REPO)/target/chroot/oresat*
+	rm -f $(IMAGE_BUILDER_REPO)/tools/setup_sdcard.sh.rej
+	rm -f $(UBOOT_REPO)/$(CONFIG)
 	make clean -C $(UBOOT_REPO)
+	make clean -C $(DEVICE_TREES)
